### ISSUE TITLE
Is sha-2 thread safe ?

### ISSUE THREAD

**Issue by damondd** [amosnier/sha-2#13]

**Comment by amosnier** [comment]
Invocations of `calc_sha_256` from multiple threads on different inputs, or on the same input is 100% thread-safe (as long as you do not modify the input data while you are calculating the SHA sum, of course, but then your code would be the one that is not thread-safe).

For the streaming API, `struct Sha_256` does not include any protection of its own, so if you use the `init`, `write` and `close` functions in multiple threads, that shall of course be on different instances of the `struct`, but if you take that basic precaution, the streaming API is thread-safe too.

Happy hacking.
