### ISSUE TITLE
Add a streaming API for computing SHA-256.

### ISSUE THREAD

**Issue by arnavyc** [amosnier/sha-2#9]
This API could be useful for computing checksum of a file without storing all of the file's data in the memory, or checksumming 2 strings together without concatenating them. Example -

```c
const char *a = "hello,";
const char *b = " world!";
uint8_t hash[32];

sha256_ctx_t ctx;
sha256_init(&ctx);
sha256_update(&ctx, a, strlen(a));
sha256_update(&ctx, b, strlen(b));
sha256_final(&ctx, hash);
```

**Comment by amosnier** [comment]
Implemented in 6e94ad4d8b8031ae7e1d48d7b4884f65f00e43d9.

That is in fact a complete rewrite, but I think the resulting structure is significantly better, because the hash value is calculated in chunks anyway. Thanks a lot for this suggestion. Enjoy!
